### ISSUE TITLE
Definieer custom properties op een logisch element niveau

### ISSUE THREAD

**Issue by joostf** [Ravirkt/look-and-feel-corporate-identity#10]
https://github.com/Ravirkt/look-and-feel-corporate-identity/blob/56e8347ccbf6b103b8a83328f06aced0d3e2c7e4/css/tumimundo.css#L4-L136

Alles in de body definieren maakt je code onoverzichtelijk en, zeker als je de waarde van de propertisch dynamisch gaat aanpassen (met verschillende states en animatie bijvoorbeeld), ga je tegen performance issues aanlopen.

Doe niet dit:

```css
body {
   ...

   /* table */
    --th-background-color: #9264f4;
    --th-border: 1px solid black;
    --td-border: 1px solid black;
    --table-border-collapse: collapse;
    --tr-padding: 5px;
    --td-padding: 5px;
    --tr-child-even-background-color: #ffffff;
    --tr-child-odd-background-color: #efd1ff;

  ...
}

```

Doe wel dit:
```css
table {
    --th-background-color: #9264f4;
    --th-border: 1px solid black;
    --td-border: 1px solid black;
    --table-border-collapse: collapse;
    --tr-padding: 5px;
    --td-padding: 5px;
    --tr-child-even-background-color: #ffffff;
    --tr-child-odd-background-color: #efd1ff;
}
```
