### ISSUE TITLE
Bepaal een consistente strategie voor het gebruik van custom properties

### ISSUE THREAD

**Issue by joostf** [Ravirkt/look-and-feel-corporate-identity#11]
https://github.com/Ravirkt/look-and-feel-corporate-identity/blob/56e8347ccbf6b103b8a83328f06aced0d3e2c7e4/css/tumimundo.css#L266-L273

Het is nu onduidelijk wanneer je wel of niet custom properties gebruikt:

Hier gebruik je voor alle properties custom properties:

```css
.input-text-form {
  width: var(--width-text-form);
  height: var(--height-text-form);
  border-radius: var(--border-radius-text-form);
  border: var(--border-text-form);
  padding: var(--padding-text-form);
  font-size: var(--font-size-text-form);
  background-color: var(--background-color-text-form);
  letter-spacing: var(--letter-spacing-text-form);
}

```

en hier voor geen van de properties:
```css
input[type="radio"] {
  appearance: none;
  width: 15px;
  height: 15px;
  border: 2px solid #000000;
}
```

Bepaal een consistente strategie en maak er afspraken over met je team (conventies)
